services:
  node:
    container_name: 'audio-community-node'
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - minio
    command: npm run start:dev
    ports:
      - 3000:3000
    restart: unless-stopped

  postgres:
    container_name: 'audio-community-postgres'
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./audio-community-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: phong
      POSTGRES_PASSWORD: phong123
      POSTGRES_DB: audio-community
    restart: unless-stopped

  minio:
    container_name: 'audio-community-minio'
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: phong
      MINIO_ROOT_PASSWORD: phong123
    restart: unless-stopped
    volumes:
      - ./audio-community-storage:/data
    command: server /data --console-address ":9090"
