export enum ErrorMessage {
  NOT_FOUND_PLAYLIST = 'NOT_FOUND_PLAYLIST',
  NOT_FOUND_ALBUM = 'NOT_FOUND_ALBUM',
  NOT_FOUND_USER = 'NOT_FOUND_USER',
  NOT_FOUND_COMMENT = 'NOT_FOUND_COMMENT',
  NOT_FOUND_AUDIO = 'NOT_FOUND_AUDIO',
  NOT_FOUND_CATEGORY = 'NOT_FOUND_CATEGORY',

  AUDIO_HAVE_EXISTED_IN_PLAYLIST = 'AUDIO_HAVE_EXISTED_IN_PLAYLIST',
  AUDIO_HAVE_NOT_EXISTED_IN_PLAYLIST = 'AUDIO_HAVE_NOT_EXISTED_IN_PLAYLIST',
  USER_HAVE_LIKED_SONG = 'USER_HAVE_LIKED_SONG',
  USER_HAVE_NOT_LIKED_SONG = 'USER_HAVE_NOT_LIKED_SONG',

  EMAIL_IS_BEING_USED = 'EMAIL_IS_BEING_USED',
  EMAIL_DOES_NOT_EXIST = 'EMAIL_DOES_NOT_EXIST',
  PASSWORD_DOES_NOT_MATCH = 'PASSWORD_DOES_NOT_MATCH',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED_TO_DO = 'UNAUTHORIZED_TO_DO',
}
